name: lab4
version: 1.0

dependencies:
  - base >= 4.7 && < 5
  - random
  - vector
  - containers


ghc-options:
  - -Wall
  - -Werror
  - -O2

library:
  source-dirs: src
  exposed_modules:
   - HaskLearn.Models.Linreg
   - HaskLearn.Main

executables:
  lab4-elf:
    main: HaskLearn.Main
    source-dirs: src
    dependencies:
      - lab4

tests:
  lab1-test-suite:
    main: spec.hs
    source-dirs: test
    dependencies:
      - base
      - hspec
      - lab4
      - QuickCheck
